### ISSUE TITLE
We should relocate data things into its own server

### ISSUE THREAD

**Issue by PeteyPii** [PeteyPii/MyLoLFantasy#39]
Having the stat tracker in the Flask server as a global variable doesn't work properly (things break with simultaneous requests and on production) so we should move the data related code into its own Node.js server that can be called locally by the Flask server

**Comment by bsankara** [comment]
Similar to that we have to move away from sqllite because writes cause a database lock -- not a issue now where everything gets updated at once every once in a while, but will be an issue if we allow manual refreshing

**Comment by joshkergan** [comment]
I'm guessing we're probably going to want atomic updates? (Like the way MongoDB works, it doesn't lock the database, but updates it object by object)

**Comment by PeteyPii** [comment]
Rewrote the whole app in Node.js. Things work a lot more smoothly now.
