### ISSUE TITLE
We should put Riot's disclaimer on the site

### ISSUE THREAD

**Issue by PeteyPii** [PeteyPii/MyLoLFantasy#51]
It is a requirement given by Riot in order to use their API. See the Riot API site for more info

**Comment by joshkergan** [comment]
Mind if I do this?

**Comment by PeteyPii** [comment]
You're absolutely welcome to! Here's the relevant quote from Riot (which I actually had trouble finding):

> You acknowledge that Your Application must prominently display the following statement in the help text, about text, or footer:
> 
> [The title of Your Application] isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.

I'm thinking to link to an about page from the footer. The text itself is a bit long to be straight in the footer IMO, and help page could be useful in the future for the app itself (e.g. an FAQ of sorts). I don't even see LoLKing and op.gg doing this attribution so maybe do some research to see how other people do it too.

**Comment by PeteyPii** [comment]
Did this in v2.0.0
